# =========================
# SERVER
# =========================
server.port=8080

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_db
spring.datasource.username=postgres
spring.datasource.password=2486

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# POSTGRESQL DIALECT
# =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# OPENROUTESERVICE
# =========================
openrouteservice.api.key=${OPENROUTE_API_KEY}
openrouteservice.api.url=https://api.heigit.org/openrouteservice
